<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Agash.Webhook.Abstractions" Version="1.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Kiota.Abstractions" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Kiota.Http.HttpClientLibrary" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Kiota.Serialization.Form" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Kiota.Serialization.Json" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Kiota.Serialization.Multipart" Version="2.0.0" />
    <PackageVersion Include="Microsoft.Kiota.Serialization.Text" Version="2.0.0" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>

  <!-- Sample packages -->
  <ItemGroup>
    <PackageVersion Include="DevTunnels.Client" Version="1.1.0" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <!-- Test packages -->
  <ItemGroup>
    <PackageVersion Include="MSTest" Version="4.3.3" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
  </ItemGroup>
</Project>
