// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Configured_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Contributions;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Donation_matches;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Donations;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Donor_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Fitness_goals;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Milestones;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Polls;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Rewards;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Schedules;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Supporting_facts;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Targets;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_distance_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_time_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.Team_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_distance_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_time_leaderboard;
using Tiltify.Client.Generated.Api.Public.Facts.Item.User_leaderboard;
using Tiltify.Client.Generated.Models;
namespace Tiltify.Client.Generated.Api.Public.Facts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\facts\{fact_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFact_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configured_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Configured_leaderboard.Configured_leaderboardRequestBuilder Configured_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Configured_leaderboard.Configured_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contributions property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Contributions.ContributionsRequestBuilder Contributions
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Contributions.ContributionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The donation_matches property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donation_matches.Donation_matchesRequestBuilder Donation_matches
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donation_matches.Donation_matchesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The donations property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donations.DonationsRequestBuilder Donations
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donations.DonationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The donor_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donor_leaderboard.Donor_leaderboardRequestBuilder Donor_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Donor_leaderboard.Donor_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fitness_goals property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Fitness_goals.Fitness_goalsRequestBuilder Fitness_goals
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Fitness_goals.Fitness_goalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The milestones property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Milestones.MilestonesRequestBuilder Milestones
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Milestones.MilestonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The polls property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Polls.PollsRequestBuilder Polls
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Polls.PollsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rewards property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Rewards.RewardsRequestBuilder Rewards
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Rewards.RewardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schedules property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Schedules.SchedulesRequestBuilder Schedules
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Schedules.SchedulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The supporting_facts property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Supporting_facts.Supporting_factsRequestBuilder Supporting_facts
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Supporting_facts.Supporting_factsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The targets property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Targets.TargetsRequestBuilder Targets
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Targets.TargetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_fitness_distance_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_distance_leaderboard.Team_fitness_distance_leaderboardRequestBuilder Team_fitness_distance_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_distance_leaderboard.Team_fitness_distance_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_fitness_time_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_time_leaderboard.Team_fitness_time_leaderboardRequestBuilder Team_fitness_time_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_fitness_time_leaderboard.Team_fitness_time_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_leaderboard.Team_leaderboardRequestBuilder Team_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.Team_leaderboard.Team_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user_fitness_distance_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_distance_leaderboard.User_fitness_distance_leaderboardRequestBuilder User_fitness_distance_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_distance_leaderboard.User_fitness_distance_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user_fitness_time_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_time_leaderboard.User_fitness_time_leaderboardRequestBuilder User_fitness_time_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_fitness_time_leaderboard.User_fitness_time_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user_leaderboard property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_leaderboard.User_leaderboardRequestBuilder User_leaderboard
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.Item.User_leaderboard.User_leaderboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFact_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts/{fact_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFact_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts/{fact_id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a fact by its ID
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Tiltify.Client.Generated.Models.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.UnprocessableEntity">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_GetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_GetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Tiltify.Client.Generated.Models.Unauthorized.CreateFromDiscriminatorValue },
                { "404", global::Tiltify.Client.Generated.Models.NotFound.CreateFromDiscriminatorValue },
                { "422", global::Tiltify.Client.Generated.Models.UnprocessableEntity.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_GetResponse>(requestInfo, global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a fact by its ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
