// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.PersonalCampaigns.Item;
namespace Tiltify.Client.Generated.Api.Public.PersonalCampaigns
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\personal-campaigns
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PersonalCampaignsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.personalCampaigns.item collection</summary>
        /// <param name="position">Personal Campaign ID</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.Item.WithPersonal_campaign_ItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.Item.WithPersonal_campaign_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("personal_campaign_id", position);
                return new global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.Item.WithPersonal_campaign_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.PersonalCampaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonalCampaignsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/personal-campaigns", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.PersonalCampaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PersonalCampaignsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/personal-campaigns", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
