// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Auction_houses;
using Tiltify.Client.Generated.Api.Public.Campaigns;
using Tiltify.Client.Generated.Api.Public.Causes;
using Tiltify.Client.Generated.Api.Public.CurrentUser;
using Tiltify.Client.Generated.Api.Public.Facts;
using Tiltify.Client.Generated.Api.Public.Fundraising_events;
using Tiltify.Client.Generated.Api.Public.LegacyRelays;
using Tiltify.Client.Generated.Api.Public.PersonalCampaigns;
using Tiltify.Client.Generated.Api.Public.Team_campaigns;
using Tiltify.Client.Generated.Api.Public.Teams;
using Tiltify.Client.Generated.Api.Public.Users;
namespace Tiltify.Client.Generated.Api.Public
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auction_houses property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Auction_houses.Auction_housesRequestBuilder Auction_houses
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Auction_houses.Auction_housesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The campaigns property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Campaigns.CampaignsRequestBuilder Campaigns
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Campaigns.CampaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The causes property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Causes.CausesRequestBuilder Causes
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Causes.CausesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The currentUser property</summary>
        public global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserRequestBuilder CurrentUser
        {
            get => new global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The facts property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.FactsRequestBuilder Facts
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.FactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fundraising_events property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Fundraising_events.Fundraising_eventsRequestBuilder Fundraising_events
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Fundraising_events.Fundraising_eventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The legacyRelays property</summary>
        public global::Tiltify.Client.Generated.Api.Public.LegacyRelays.LegacyRelaysRequestBuilder LegacyRelays
        {
            get => new global::Tiltify.Client.Generated.Api.Public.LegacyRelays.LegacyRelaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The personalCampaigns property</summary>
        public global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.PersonalCampaignsRequestBuilder PersonalCampaigns
        {
            get => new global::Tiltify.Client.Generated.Api.Public.PersonalCampaigns.PersonalCampaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_campaigns property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Team_campaignsRequestBuilder Team_campaigns
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Team_campaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Users.UsersRequestBuilder Users
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
