// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs;
namespace Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\auction_houses\by\cause
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CauseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The slugs property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.SlugsRequestBuilder Slugs
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.SlugsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.CauseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CauseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses/by/cause", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.CauseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CauseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses/by/cause", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
