// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Api.Public.Teams.Item.Team_campaigns
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSupporting_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invite_only")]
        #pragma warning disable CS1591
        Invite_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
    }
}
