// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuctionHouse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount raised directly by this auction house</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? AmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money AmountRaised { get; set; }
#endif
        /// <summary>An Image includes the html properties necessary to render an &lt;img&gt; tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Image? Avatar { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Image Avatar { get; set; }
#endif
        /// <summary>An Image includes the html properties necessary to render an &lt;img&gt; tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Image? Banner { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Image Banner { get; set; }
#endif
        /// <summary>The ID for the campaign that this auction house is supporting.</summary>
        public Guid? CampaignId { get; set; }
        /// <summary>The ID for the cause that this auction house is supporting.</summary>
        public Guid? CauseId { get; set; }
        /// <summary>A short description about this auction house</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID for the fundraising event that this auction house is supporting.</summary>
        public Guid? FundraisingEventId { get; set; }
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>When the auction house was created</summary>
        public DateTimeOffset? InsertedAt { get; set; }
        /// <summary>The name of this auction house</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The amount of money that is pending from completed auction items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? PledgedAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money PledgedAmountRaised { get; set; }
#endif
        /// <summary>The amount of money that is pending from completed auction items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? PledgedTotalAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money PledgedTotalAmountRaised { get; set; }
#endif
        /// <summary>When the auction house was last published</summary>
        public DateTimeOffset? PublishedAt { get; set; }
        /// <summary>When the auction house was retired</summary>
        public DateTimeOffset? RetiredAt { get; set; }
        /// <summary>This is a url slug used for the given resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The status of this auction house</summary>
        public global::Tiltify.Client.Generated.Models.AuctionHouse_status? Status { get; set; }
        /// <summary>The ID for the team event that this auction house is supporting.</summary>
        public Guid? TeamEventId { get; set; }
        /// <summary>The amount raised by this auction house</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? TotalAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money TotalAmountRaised { get; set; }
#endif
        /// <summary>When the auction house details were last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>This is the full url for the auction house.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The ID for a User that owns this auction house.</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.AuctionHouse"/> and sets the default values.
        /// </summary>
        public AuctionHouse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.AuctionHouse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.AuctionHouse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.AuctionHouse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_raised", n => { AmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "avatar", n => { Avatar = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue); } },
                { "banner", n => { Banner = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue); } },
                { "campaign_id", n => { CampaignId = n.GetGuidValue(); } },
                { "cause_id", n => { CauseId = n.GetGuidValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "fundraising_event_id", n => { FundraisingEventId = n.GetGuidValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inserted_at", n => { InsertedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pledged_amount_raised", n => { PledgedAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "pledged_total_amount_raised", n => { PledgedTotalAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "published_at", n => { PublishedAt = n.GetDateTimeOffsetValue(); } },
                { "retired_at", n => { RetiredAt = n.GetDateTimeOffsetValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Tiltify.Client.Generated.Models.AuctionHouse_status>(); } },
                { "team_event_id", n => { TeamEventId = n.GetGuidValue(); } },
                { "total_amount_raised", n => { TotalAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("amount_raised", AmountRaised);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Image>("avatar", Avatar);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Image>("banner", Banner);
            writer.WriteGuidValue("campaign_id", CampaignId);
            writer.WriteGuidValue("cause_id", CauseId);
            writer.WriteStringValue("description", Description);
            writer.WriteGuidValue("fundraising_event_id", FundraisingEventId);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("inserted_at", InsertedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("pledged_amount_raised", PledgedAmountRaised);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("pledged_total_amount_raised", PledgedTotalAmountRaised);
            writer.WriteDateTimeOffsetValue("published_at", PublishedAt);
            writer.WriteDateTimeOffsetValue("retired_at", RetiredAt);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.AuctionHouse_status>("status", Status);
            writer.WriteGuidValue("team_event_id", TeamEventId);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("total_amount_raised", TotalAmountRaised);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteGuidValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
