// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuctionBid : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of the bid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? Amount { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money Amount { get; set; }
#endif
        /// <summary>The ID for the auction house of this auction bid.</summary>
        public Guid? AuctionHouseId { get; set; }
        /// <summary>The ID for the auction item of this auction bid.</summary>
        public Guid? AuctionItemId { get; set; }
        /// <summary>Whether or not this bid is the current winning bid</summary>
        public bool? CurrentWinner { get; set; }
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>When the auction bid was created</summary>
        public DateTimeOffset? InsertedAt { get; set; }
        /// <summary>The public name of the bidder</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicName { get; set; }
#nullable restore
#else
        public string PublicName { get; set; }
#endif
        /// <summary>When the auction bid was removed</summary>
        public DateTimeOffset? RemovedAt { get; set; }
        /// <summary>When the auction bid was updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.AuctionBid"/> and sets the default values.
        /// </summary>
        public AuctionBid()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.AuctionBid"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.AuctionBid CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.AuctionBid();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "auction_house_id", n => { AuctionHouseId = n.GetGuidValue(); } },
                { "auction_item_id", n => { AuctionItemId = n.GetGuidValue(); } },
                { "current_winner", n => { CurrentWinner = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inserted_at", n => { InsertedAt = n.GetDateTimeOffsetValue(); } },
                { "public_name", n => { PublicName = n.GetStringValue(); } },
                { "removed_at", n => { RemovedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("amount", Amount);
            writer.WriteGuidValue("auction_house_id", AuctionHouseId);
            writer.WriteGuidValue("auction_item_id", AuctionItemId);
            writer.WriteBoolValue("current_winner", CurrentWinner);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("inserted_at", InsertedAt);
            writer.WriteStringValue("public_name", PublicName);
            writer.WriteDateTimeOffsetValue("removed_at", RemovedAt);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
