// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuctionItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>When the auction item was activated</summary>
        public DateTimeOffset? ActivatedAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the auction item was completed</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The description of this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>When the auction item ends</summary>
        public DateTimeOffset? EndsAt { get; set; }
        /// <summary>The amount of the auction item if it was sold</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? FairMarketValue { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money FairMarketValue { get; set; }
#endif
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>Images for this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Tiltify.Client.Generated.Models.Image>? Images { get; set; }
#nullable restore
#else
        public List<global::Tiltify.Client.Generated.Models.Image> Images { get; set; }
#endif
        /// <summary>When the auction item was created</summary>
        public DateTimeOffset? InsertedAt { get; set; }
        /// <summary>The legal information of this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Legal { get; set; }
#nullable restore
#else
        public string Legal { get; set; }
#endif
        /// <summary>The name of this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The rules of this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rules { get; set; }
#nullable restore
#else
        public string Rules { get; set; }
#endif
        /// <summary>The short description of this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortDescription { get; set; }
#nullable restore
#else
        public string ShortDescription { get; set; }
#endif
        /// <summary>The starting bid amount for this auction item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? StartingBid { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money StartingBid { get; set; }
#endif
        /// <summary>When the auction item starts</summary>
        public DateTimeOffset? StartsAt { get; set; }
        /// <summary>The status of this auction item</summary>
        public global::Tiltify.Client.Generated.Models.AuctionItem_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.AuctionItem"/> and sets the default values.
        /// </summary>
        public AuctionItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.AuctionItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.AuctionItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.AuctionItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activated_at", n => { ActivatedAt = n.GetDateTimeOffsetValue(); } },
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "ends_at", n => { EndsAt = n.GetDateTimeOffsetValue(); } },
                { "fair_market_value", n => { FairMarketValue = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue)?.AsList(); } },
                { "inserted_at", n => { InsertedAt = n.GetDateTimeOffsetValue(); } },
                { "legal", n => { Legal = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "rules", n => { Rules = n.GetStringValue(); } },
                { "short_description", n => { ShortDescription = n.GetStringValue(); } },
                { "starting_bid", n => { StartingBid = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "starts_at", n => { StartsAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Tiltify.Client.Generated.Models.AuctionItem_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("activated_at", ActivatedAt);
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("ends_at", EndsAt);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("fair_market_value", FairMarketValue);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.Image>("images", Images);
            writer.WriteDateTimeOffsetValue("inserted_at", InsertedAt);
            writer.WriteStringValue("legal", Legal);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("rules", Rules);
            writer.WriteStringValue("short_description", ShortDescription);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("starting_bid", StartingBid);
            writer.WriteDateTimeOffsetValue("starts_at", StartsAt);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.AuctionItem_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
