// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Contribution : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount donated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? Amount { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money Amount { get; set; }
#endif
        /// <summary>Timestamp of when the contribution was completed.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>Note left by donor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DonorComment { get; set; }
#nullable restore
#else
        public string DonorComment { get; set; }
#endif
        /// <summary>Publically visible donor name. This may be set to &apos;Anonymous&apos; if the contribution was anonymous or moderated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DonorName { get; set; }
#nullable restore
#else
        public string DonorName { get; set; }
#endif
        /// <summary>The list of matches consumed by this contribution</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Tiltify.Client.Generated.Models.GiftMatch>? GiftMatches { get; set; }
#nullable restore
#else
        public List<global::Tiltify.Client.Generated.Models.GiftMatch> GiftMatches { get; set; }
#endif
        /// <summary>Unique Identifier for the contribution.</summary>
        public Guid? Id { get; set; }
        /// <summary>Whether or not the contribution is the result of a GiftMatch</summary>
        public bool? IsMatch { get; set; }
        /// <summary>ID of the campaign donated to</summary>
        public Guid? PersonalCampaignId { get; set; }
        /// <summary>The ID for a Poll, if one was donated toward.</summary>
        public Guid? PollId { get; set; }
        /// <summary>The ID for a PollOption, if one was donated toward.</summary>
        public Guid? PollOptionId { get; set; }
        /// <summary>The reward_claims property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Tiltify.Client.Generated.Models.RewardClaim>? RewardClaims { get; set; }
#nullable restore
#else
        public List<global::Tiltify.Client.Generated.Models.RewardClaim> RewardClaims { get; set; }
#endif
        /// <summary>The ID for a Target, if one was donated toward.</summary>
        public Guid? TargetId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.Contribution"/> and sets the default values.
        /// </summary>
        public Contribution()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.Contribution"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.Contribution CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.Contribution();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "donor_comment", n => { DonorComment = n.GetStringValue(); } },
                { "donor_name", n => { DonorName = n.GetStringValue(); } },
                { "gift_matches", n => { GiftMatches = n.GetCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.GiftMatch>(global::Tiltify.Client.Generated.Models.GiftMatch.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "is_match", n => { IsMatch = n.GetBoolValue(); } },
                { "personal_campaign_id", n => { PersonalCampaignId = n.GetGuidValue(); } },
                { "poll_id", n => { PollId = n.GetGuidValue(); } },
                { "poll_option_id", n => { PollOptionId = n.GetGuidValue(); } },
                { "reward_claims", n => { RewardClaims = n.GetCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.RewardClaim>(global::Tiltify.Client.Generated.Models.RewardClaim.CreateFromDiscriminatorValue)?.AsList(); } },
                { "target_id", n => { TargetId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("amount", Amount);
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteStringValue("donor_comment", DonorComment);
            writer.WriteStringValue("donor_name", DonorName);
            writer.WriteCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.GiftMatch>("gift_matches", GiftMatches);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("is_match", IsMatch);
            writer.WriteGuidValue("personal_campaign_id", PersonalCampaignId);
            writer.WriteGuidValue("poll_id", PollId);
            writer.WriteGuidValue("poll_option_id", PollOptionId);
            writer.WriteCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.RewardClaim>("reward_claims", RewardClaims);
            writer.WriteGuidValue("target_id", TargetId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
