// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Tiltify.Client.Generated.Models.Campaign"/>, <see cref="global::Tiltify.Client.Generated.Models.TeamCampaign"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Event : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Tiltify.Client.Generated.Models.Campaign"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Campaign? Campaign { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Campaign Campaign { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Tiltify.Client.Generated.Models.TeamCampaign"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.TeamCampaign? TeamCampaign { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.TeamCampaign TeamCampaign { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.Event"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.Event CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Tiltify.Client.Generated.Models.Event();
            if("Campaign".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Campaign = new global::Tiltify.Client.Generated.Models.Campaign();
            }
            else if("TeamCampaign".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TeamCampaign = new global::Tiltify.Client.Generated.Models.TeamCampaign();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Campaign != null)
            {
                return Campaign.GetFieldDeserializers();
            }
            else if(TeamCampaign != null)
            {
                return TeamCampaign.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Campaign != null)
            {
                writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Campaign>(null, Campaign);
            }
            else if(TeamCampaign != null)
            {
                writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.TeamCampaign>(null, TeamCampaign);
            }
        }
    }
}
#pragma warning restore CS0618
