// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>
    /// Facts are all fundraising initiatives on Tiltify by individuals, teams, or causes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Fact : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount raised directly by this fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? AmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money AmountRaised { get; set; }
#endif
        /// <summary>An Image includes the html properties necessary to render an &lt;img&gt; tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Image? Avatar { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Image Avatar { get; set; }
#endif
        /// <summary>The datetime the campaign will allow supporting facts to be published in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanPublishSupportingAt { get; set; }
#nullable restore
#else
        public string CanPublishSupportingAt { get; set; }
#endif
        /// <summary>A short description about this fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>This is the donate url for the fact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DonateUrl { get; set; }
#nullable restore
#else
        public string DonateUrl { get; set; }
#endif
        /// <summary>An optional date when this fact ends.</summary>
        [Obsolete("")]
        public Date? EndsAt { get; set; }
        /// <summary>The datetime the fact will stop accepting registrations in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndSupportingAt { get; set; }
#nullable restore
#else
        public string EndSupportingAt { get; set; }
#endif
        /// <summary>This is the full url for the fact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FactUrl { get; set; }
#nullable restore
#else
        public string FactUrl { get; set; }
#endif
        /// <summary>The current goal of the fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? Goal { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money Goal { get; set; }
#endif
        /// <summary>Whether or not this fact has schedule items</summary>
        public bool? HasSchedule { get; set; }
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>When the fact was created</summary>
        public DateTimeOffset? InsertedAt { get; set; }
        /// <summary>The livestream information for this fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Fact_livestream? Livestream { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Fact_livestream Livestream { get; set; }
#endif
        /// <summary>The name of this fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The original goal of the fact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? OriginalGoal { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money OriginalGoal { get; set; }
#endif
        /// <summary>The parent_facts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Tiltify.Client.Generated.Models.SimpleFact>? ParentFacts { get; set; }
#nullable restore
#else
        public List<global::Tiltify.Client.Generated.Models.SimpleFact> ParentFacts { get; set; }
#endif
        /// <summary>When the fact was last published</summary>
        public DateTimeOffset? PublishedAt { get; set; }
        /// <summary>When the fact was retired</summary>
        public DateTimeOffset? RetiredAt { get; set; }
        /// <summary>This is a url slug used for the given resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>An optional date when this fact starts.</summary>
        [Obsolete("")]
        public Date? StartsAt { get; set; }
        /// <summary>The datetime the fact will start accepting registrations in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartSupportingAt { get; set; }
#nullable restore
#else
        public string StartSupportingAt { get; set; }
#endif
        /// <summary>The status of this fact</summary>
        public global::Tiltify.Client.Generated.Models.Fact_status? Status { get; set; }
        /// <summary>The amount raised by this fact and all supporting facts</summary>
        public global::Tiltify.Client.Generated.Models.Fact_supporting_type? SupportingType { get; set; }
        /// <summary>The team that owns this fact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Team? Team { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Team Team { get; set; }
#endif
        /// <summary>The amount raised by this fact and all supporting facts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? TotalAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money TotalAmountRaised { get; set; }
#endif
        /// <summary>When the fact details were last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The User that owns this fact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.User? User { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.Fact"/> and sets the default values.
        /// </summary>
        public Fact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.Fact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.Fact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.Fact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_raised", n => { AmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "avatar", n => { Avatar = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue); } },
                { "can_publish_supporting_at", n => { CanPublishSupportingAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "donate_url", n => { DonateUrl = n.GetStringValue(); } },
                { "end_supporting_at", n => { EndSupportingAt = n.GetStringValue(); } },
                { "ends_at", n => { EndsAt = n.GetDateValue(); } },
                { "fact_url", n => { FactUrl = n.GetStringValue(); } },
                { "goal", n => { Goal = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "has_schedule", n => { HasSchedule = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inserted_at", n => { InsertedAt = n.GetDateTimeOffsetValue(); } },
                { "livestream", n => { Livestream = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Fact_livestream>(global::Tiltify.Client.Generated.Models.Fact_livestream.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "original_goal", n => { OriginalGoal = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "parent_facts", n => { ParentFacts = n.GetCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.SimpleFact>(global::Tiltify.Client.Generated.Models.SimpleFact.CreateFromDiscriminatorValue)?.AsList(); } },
                { "published_at", n => { PublishedAt = n.GetDateTimeOffsetValue(); } },
                { "retired_at", n => { RetiredAt = n.GetDateTimeOffsetValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "start_supporting_at", n => { StartSupportingAt = n.GetStringValue(); } },
                { "starts_at", n => { StartsAt = n.GetDateValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Tiltify.Client.Generated.Models.Fact_status>(); } },
                { "supporting_type", n => { SupportingType = n.GetEnumValue<global::Tiltify.Client.Generated.Models.Fact_supporting_type>(); } },
                { "team", n => { Team = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Team>(global::Tiltify.Client.Generated.Models.Team.CreateFromDiscriminatorValue); } },
                { "total_amount_raised", n => { TotalAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Tiltify.Client.Generated.Models.User>(global::Tiltify.Client.Generated.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("amount_raised", AmountRaised);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Image>("avatar", Avatar);
            writer.WriteStringValue("can_publish_supporting_at", CanPublishSupportingAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("donate_url", DonateUrl);
            writer.WriteDateValue("ends_at", EndsAt);
            writer.WriteStringValue("end_supporting_at", EndSupportingAt);
            writer.WriteStringValue("fact_url", FactUrl);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("goal", Goal);
            writer.WriteBoolValue("has_schedule", HasSchedule);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("inserted_at", InsertedAt);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Fact_livestream>("livestream", Livestream);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("original_goal", OriginalGoal);
            writer.WriteCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.SimpleFact>("parent_facts", ParentFacts);
            writer.WriteDateTimeOffsetValue("published_at", PublishedAt);
            writer.WriteDateTimeOffsetValue("retired_at", RetiredAt);
            writer.WriteStringValue("slug", Slug);
            writer.WriteDateValue("starts_at", StartsAt);
            writer.WriteStringValue("start_supporting_at", StartSupportingAt);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.Fact_status>("status", Status);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.Fact_supporting_type>("supporting_type", SupportingType);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Team>("team", Team);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("total_amount_raised", TotalAmountRaised);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
