// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>The status of this fact</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Fact_status
    {
        [EnumMember(Value = "unpublished")]
        #pragma warning disable CS1591
        Unpublished,
        #pragma warning restore CS1591
        [EnumMember(Value = "published")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "retired")]
        #pragma warning disable CS1591
        Retired,
        #pragma warning restore CS1591
    }
}
