// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>The amount raised by this fact and all supporting facts</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Fact_supporting_type
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_only")]
        #pragma warning disable CS1591
        Invite_only,
        #pragma warning restore CS1591
    }
}
