// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>The Fitness Goal distance unit if it exists</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FitnessGoal_distance_unit
    {
        [EnumMember(Value = "meter")]
        #pragma warning disable CS1591
        Meter,
        #pragma warning restore CS1591
        [EnumMember(Value = "kilometer")]
        #pragma warning disable CS1591
        Kilometer,
        #pragma warning restore CS1591
        [EnumMember(Value = "mile")]
        #pragma warning disable CS1591
        Mile,
        #pragma warning restore CS1591
    }
}
