// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>The Fitness Goal Type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FitnessGoal_type
    {
        [EnumMember(Value = "distance")]
        #pragma warning disable CS1591
        Distance,
        #pragma warning restore CS1591
        [EnumMember(Value = "step")]
        #pragma warning disable CS1591
        Step,
        #pragma warning restore CS1591
        [EnumMember(Value = "time")]
        #pragma warning disable CS1591
        Time,
        #pragma warning restore CS1591
    }
}
