// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>measured unit</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MeasuredUnit_unit
    {
        [EnumMember(Value = "seconds")]
        #pragma warning disable CS1591
        Seconds,
        #pragma warning restore CS1591
        [EnumMember(Value = "kilometer")]
        #pragma warning disable CS1591
        Kilometer,
        #pragma warning restore CS1591
        [EnumMember(Value = "mile")]
        #pragma warning disable CS1591
        Mile,
        #pragma warning restore CS1591
    }
}
