// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>
    /// Object returned for paginated API responses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaginatedResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Tiltify.Client.Generated.Models.PaginatedResponse_data>? Data { get; set; }
#nullable restore
#else
        public List<global::Tiltify.Client.Generated.Models.PaginatedResponse_data> Data { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.PaginatedResponse_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.PaginatedResponse_metadata Metadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.PaginatedResponse"/> and sets the default values.
        /// </summary>
        public PaginatedResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.PaginatedResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.PaginatedResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.PaginatedResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.PaginatedResponse_data>(global::Tiltify.Client.Generated.Models.PaginatedResponse_data.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Tiltify.Client.Generated.Models.PaginatedResponse_metadata>(global::Tiltify.Client.Generated.Models.PaginatedResponse_metadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Tiltify.Client.Generated.Models.PaginatedResponse_data>("data", Data);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.PaginatedResponse_metadata>("metadata", Metadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
