// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Tiltify.Client.Generated.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PersonalCampaign : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount raised directly by this campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? AmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money AmountRaised { get; set; }
#endif
        /// <summary>An Image includes the html properties necessary to render an &lt;img&gt; tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Image? Avatar { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Image Avatar { get; set; }
#endif
        /// <summary>A short description about this campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>This is the donate url for the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DonateUrl { get; set; }
#nullable restore
#else
        public string DonateUrl { get; set; }
#endif
        /// <summary>The name of who the personal campaign is fundraising for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FundraisingForName { get; set; }
#nullable restore
#else
        public string FundraisingForName { get; set; }
#endif
        /// <summary>If the personal campaign is fundraising for the owner</summary>
        public bool? FundraisingForSelf { get; set; }
        /// <summary>The current goal of the campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? Goal { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money Goal { get; set; }
#endif
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>When the campaign was created</summary>
        public DateTimeOffset? InsertedAt { get; set; }
        /// <summary>The name of this campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The original goal of the campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? OriginalGoal { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money OriginalGoal { get; set; }
#endif
        /// <summary>When the campaign was last published</summary>
        public DateTimeOffset? PublishedAt { get; set; }
        /// <summary>When the campaign was retired</summary>
        public DateTimeOffset? RetiredAt { get; set; }
        /// <summary>This is a url slug used for the given resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The status of this campaign</summary>
        public global::Tiltify.Client.Generated.Models.PersonalCampaign_status? Status { get; set; }
        /// <summary>The amount raised by this campaign and all supporting campaigns</summary>
        public global::Tiltify.Client.Generated.Models.PersonalCampaign_supporting_type? SupportingType { get; set; }
        /// <summary>The amount raised by this campaign and all supporting campaigns</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? TotalAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money TotalAmountRaised { get; set; }
#endif
        /// <summary>When the campaign details were last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>This is the full url for the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The User that owns this campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.User? User { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.User User { get; set; }
#endif
        /// <summary>The ID for a User that owns this campaign.</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Models.PersonalCampaign"/> and sets the default values.
        /// </summary>
        public PersonalCampaign()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Models.PersonalCampaign"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Models.PersonalCampaign CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Models.PersonalCampaign();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_raised", n => { AmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "avatar", n => { Avatar = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "donate_url", n => { DonateUrl = n.GetStringValue(); } },
                { "fundraising_for_name", n => { FundraisingForName = n.GetStringValue(); } },
                { "fundraising_for_self", n => { FundraisingForSelf = n.GetBoolValue(); } },
                { "goal", n => { Goal = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inserted_at", n => { InsertedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "original_goal", n => { OriginalGoal = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "published_at", n => { PublishedAt = n.GetDateTimeOffsetValue(); } },
                { "retired_at", n => { RetiredAt = n.GetDateTimeOffsetValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Tiltify.Client.Generated.Models.PersonalCampaign_status>(); } },
                { "supporting_type", n => { SupportingType = n.GetEnumValue<global::Tiltify.Client.Generated.Models.PersonalCampaign_supporting_type>(); } },
                { "total_amount_raised", n => { TotalAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Tiltify.Client.Generated.Models.User>(global::Tiltify.Client.Generated.Models.User.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("amount_raised", AmountRaised);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Image>("avatar", Avatar);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("donate_url", DonateUrl);
            writer.WriteStringValue("fundraising_for_name", FundraisingForName);
            writer.WriteBoolValue("fundraising_for_self", FundraisingForSelf);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("goal", Goal);
            writer.WriteGuidValue("id", Id);
            writer.WriteDateTimeOffsetValue("inserted_at", InsertedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("original_goal", OriginalGoal);
            writer.WriteDateTimeOffsetValue("published_at", PublishedAt);
            writer.WriteDateTimeOffsetValue("retired_at", RetiredAt);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.PersonalCampaign_status>("status", Status);
            writer.WriteEnumValue<global::Tiltify.Client.Generated.Models.PersonalCampaign_supporting_type>("supporting_type", SupportingType);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("total_amount_raised", TotalAmountRaised);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.User>("user", User);
            writer.WriteGuidValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
