// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>Internal key for the role</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Role_key
    {
        [EnumMember(Value = "team_super_admin")]
        #pragma warning disable CS1591
        Team_super_admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_admin")]
        #pragma warning disable CS1591
        Team_admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_user_manager")]
        #pragma warning disable CS1591
        Team_user_manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_event_manager")]
        #pragma warning disable CS1591
        Team_event_manager,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_member")]
        #pragma warning disable CS1591
        Team_member,
        #pragma warning restore CS1591
    }
}
