// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Models
{
    /// <summary>The usage type of this fact.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SimpleFact_usage_type
    {
        [EnumMember(Value = "auction_house")]
        #pragma warning disable CS1591
        Auction_house,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "cause")]
        #pragma warning disable CS1591
        Cause,
        #pragma warning restore CS1591
        [EnumMember(Value = "fundraising_event_activation")]
        #pragma warning disable CS1591
        Fundraising_event_activation,
        #pragma warning restore CS1591
        [EnumMember(Value = "personal_campaign")]
        #pragma warning disable CS1591
        Personal_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_campaign")]
        #pragma warning disable CS1591
        Team_campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_event")]
        #pragma warning disable CS1591
        Team_event,
        #pragma warning restore CS1591
    }
}
