// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Api.Public.Fundraising_events.Item.Team_leaderboard
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTime_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "weekly")]
        #pragma warning disable CS1591
        Weekly,
        #pragma warning restore CS1591
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "yearly")]
        #pragma warning disable CS1591
        Yearly,
        #pragma warning restore CS1591
        [EnumMember(Value = "ytd")]
        #pragma warning disable CS1591
        Ytd,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
