// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Tiltify.Client.Generated.Models;
namespace Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\team_campaigns\{team_campaign_id}\donor_leaderboards
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Donor_leaderboardsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Donor_leaderboardsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns/{team_campaign_id}/donor_leaderboards{?after*,before*,limit*,time_type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Donor_leaderboardsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns/{team_campaign_id}/donor_leaderboards{?after*,before*,limit*,time_type*}", rawUrl)
        {
        }
        /// <summary>
        /// List top donors
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Tiltify.Client.Generated.Models.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.UnprocessableEntity">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsGetResponse?> GetAsync(Action<RequestConfiguration<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder.Donor_leaderboardsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsGetResponse> GetAsync(Action<RequestConfiguration<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder.Donor_leaderboardsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Tiltify.Client.Generated.Models.Unauthorized.CreateFromDiscriminatorValue },
                { "404", global::Tiltify.Client.Generated.Models.NotFound.CreateFromDiscriminatorValue },
                { "422", global::Tiltify.Client.Generated.Models.UnprocessableEntity.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsGetResponse>(requestInfo, global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List top donors
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder.Donor_leaderboardsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder.Donor_leaderboardsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.Donor_leaderboardsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List top donors
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Donor_leaderboardsRequestBuilderGetQueryParameters 
        {
            /// <summary>Returns records after the given cursor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>Returns records before the given cursor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("before")]
            public string? Before { get; set; }
#nullable restore
#else
            [QueryParameter("before")]
            public string Before { get; set; }
#endif
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The time range to use in leaderboard generation</summary>
            [QueryParameter("time_type")]
            public global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Donor_leaderboards.GetTime_typeQueryParameterType? TimeType { get; set; }
        }
    }
}
#pragma warning restore CS0618
