// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.Item;
namespace Tiltify.Client.Generated.Api.Public.Facts.By.Slugs
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\facts\by\slugs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SlugsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.facts.by.slugs.item collection</summary>
        /// <param name="position">User (@) or Team (+) Slug</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.Item.WithSlugItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.Item.WithSlugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("slug", position);
                return new global::Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.Item.WithSlugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.SlugsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts/by/slugs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.By.Slugs.SlugsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts/by/slugs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
