// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Causes.Item;
namespace Tiltify.Client.Generated.Api.Public.Causes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\causes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CausesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.causes.item collection</summary>
        /// <param name="position">Cause ID</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Causes.Item.WithCause_ItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Causes.Item.WithCause_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("cause_id", position);
                return new global::Tiltify.Client.Generated.Api.Public.Causes.Item.WithCause_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Causes.CausesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CausesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/causes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Causes.CausesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CausesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/causes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
