<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UserSecretsId>Tiltify.Client.Sample</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tiltify.Client\Tiltify.Client.csproj" />
    <ProjectReference Include="..\..\src\Tiltify.Client.DependencyInjection\Tiltify.Client.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Tiltify.Client.AspNetCore\Tiltify.Client.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevTunnels.Client" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
