// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.Supporting_campaigns
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "published")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
        [EnumMember(Value = "retired")]
        #pragma warning disable CS1591
        Retired,
        #pragma warning restore CS1591
    }
}
