// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Facts.By;
using Tiltify.Client.Generated.Api.Public.Facts.Item;
namespace Tiltify.Client.Generated.Api.Public.Facts
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\facts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The by property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Facts.By.ByRequestBuilder By
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Facts.By.ByRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.facts.item collection</summary>
        /// <param name="position">Fact ID</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fact_id", position);
                return new global::Tiltify.Client.Generated.Api.Public.Facts.Item.WithFact_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.FactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Facts.FactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/facts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
