// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Tiltify.Client.Generated.Api.Public.Teams.Item.Members;
using Tiltify.Client.Generated.Api.Public.Teams.Item.Team_campaigns;
using Tiltify.Client.Generated.Models;
namespace Tiltify.Client.Generated.Api.Public.Teams.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\teams\{team_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTeam_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The members property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Teams.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Teams.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_campaigns property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Teams.Item.Team_campaigns.Team_campaignsRequestBuilder Team_campaigns
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Teams.Item.Team_campaigns.Team_campaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeam_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/teams/{team_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeam_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/teams/{team_id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a team by its ID
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Tiltify.Client.Generated.Models.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Tiltify.Client.Generated.Models.UnprocessableEntity">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_GetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_GetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Tiltify.Client.Generated.Models.Unauthorized.CreateFromDiscriminatorValue },
                { "404", global::Tiltify.Client.Generated.Models.NotFound.CreateFromDiscriminatorValue },
                { "422", global::Tiltify.Client.Generated.Models.UnprocessableEntity.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_GetResponse>(requestInfo, global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a team by its ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Tiltify.Client.Generated.Api.Public.Teams.Item.WithTeam_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
