// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Team_campaigns.By;
using Tiltify.Client.Generated.Api.Public.Team_campaigns.Item;
namespace Tiltify.Client.Generated.Api.Public.Team_campaigns
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\team_campaigns
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Team_campaignsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The by property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Team_campaigns.By.ByRequestBuilder By
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Team_campaigns.By.ByRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.team_campaigns.item collection</summary>
        /// <param name="position">Team Campaign ID</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.WithTeam_campaign_ItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.WithTeam_campaign_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("team_campaign_id", position);
                return new global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Item.WithTeam_campaign_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Team_campaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_campaignsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Team_campaigns.Team_campaignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_campaignsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/team_campaigns", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
