// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
using Tiltify.Client.Generated.Models;
namespace Tiltify.Client.Generated.Api.Public.CurrentUser
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrentUserGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An Image includes the html properties necessary to render an &lt;img&gt; tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Image? Avatar { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Image Avatar { get; set; }
#endif
        /// <summary>The description section on a user&apos;s profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Unique Identifier for the Object. UUID</summary>
        public Guid? Id { get; set; }
        /// <summary>Legacy numeric ID of the object. If your app is dependent on this field, please migrate to id. This will be deprecated in the next version of the API.</summary>
        [Obsolete("")]
        public double? LegacyId { get; set; }
        /// <summary>This is a url slug used for the given resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>An object with various social usernames and links</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Social? Social { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Social Social { get; set; }
#endif
        /// <summary>The total amount raised by this user represented in USD.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Tiltify.Client.Generated.Models.Money? TotalAmountRaised { get; set; }
#nullable restore
#else
        public global::Tiltify.Client.Generated.Models.Money TotalAmountRaised { get; set; }
#endif
        /// <summary>This is the full url for the user profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The user&apos;s username</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserGetResponse_data"/> and sets the default values.
        /// </summary>
        public CurrentUserGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Tiltify.Client.Generated.Api.Public.CurrentUser.CurrentUserGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar", n => { Avatar = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Image>(global::Tiltify.Client.Generated.Models.Image.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "legacy_id", n => { LegacyId = n.GetDoubleValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "social", n => { Social = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Social>(global::Tiltify.Client.Generated.Models.Social.CreateFromDiscriminatorValue); } },
                { "total_amount_raised", n => { TotalAmountRaised = n.GetObjectValue<global::Tiltify.Client.Generated.Models.Money>(global::Tiltify.Client.Generated.Models.Money.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Image>("avatar", Avatar);
            writer.WriteStringValue("description", Description);
            writer.WriteGuidValue("id", Id);
            writer.WriteDoubleValue("legacy_id", LegacyId);
            writer.WriteStringValue("slug", Slug);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Social>("social", Social);
            writer.WriteObjectValue<global::Tiltify.Client.Generated.Models.Money>("total_amount_raised", TotalAmountRaised);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
