// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Auction_houses.By;
using Tiltify.Client.Generated.Api.Public.Auction_houses.Item;
namespace Tiltify.Client.Generated.Api.Public.Auction_houses
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\auction_houses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Auction_housesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The by property</summary>
        public global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.ByRequestBuilder By
        {
            get => new global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.ByRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.auction_houses.item collection</summary>
        /// <param name="position">Auction House ID</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.Item.WithAuction_house_ItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Auction_houses.Item.WithAuction_house_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("auction_house_id", position);
                return new global::Tiltify.Client.Generated.Api.Public.Auction_houses.Item.WithAuction_house_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.Auction_housesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Auction_housesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.Auction_housesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Auction_housesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
