// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.Item;
namespace Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\auction_houses\by\cause\slugs\{cause_slug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCause_slugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Tiltify.Client.Generated.api.public.auction_houses.by.cause.slugs.item.item collection</summary>
        /// <param name="position">Auction house slug</param>
        /// <returns>A <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.Item.WithAuction_house_slugItemRequestBuilder"/></returns>
        public global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.Item.WithAuction_house_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("auction_house_slug", position);
                return new global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.Item.WithAuction_house_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.WithCause_slugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCause_slugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses/by/cause/slugs/{cause_slug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tiltify.Client.Generated.Api.Public.Auction_houses.By.Cause.Slugs.Item.WithCause_slugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCause_slugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/auction_houses/by/cause/slugs/{cause_slug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
