using Tiltify.Client.Models;

namespace Tiltify.Client.Events;

/// <summary>
/// Base type for all normalized Tiltify webhook events.
/// </summary>
public abstract record TiltifyWebhookEvent
{
    /// <summary>Gets the unique delivery identifier from the webhook meta envelope.</summary>
    public required string DeliveryId { get; init; }

    /// <summary>Gets the event name (e.g. <c>public:direct:donation_updated</c>).</summary>
    public required string EventName { get; init; }

    /// <summary>Gets the ISO 8601 timestamp when the event was generated by Tiltify.</summary>
    public required string GeneratedAt { get; init; }

    /// <summary>Gets the full metadata envelope.</summary>
    public required TiltifyWebhookMeta Meta { get; init; }
}
